// ============================================================================
// Type Definitions for EchoGuard Database Schema
// ============================================================================

export type UserRole = "agent" | "supervisor" | "admin";
export type EscalationRisk = "low" | "medium" | "high";
export type AlertSeverity = "low" | "medium" | "high";
export type CoachingPriority = "low" | "medium" | "high";

// ============================================================================
// USER
// ============================================================================
export interface User {
  id: string;
  name: string;
  email: string;
  password_hash?: string; // Not returned in API responses
  role: UserRole;
  supervisor_id: string | null;
  city: string | null;
  created_at: string;
  updated_at: string;
}

export interface UserResponse {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  supervisorId: string | null;
  city: string | null;
}

// ============================================================================
// CALL
// ============================================================================
export interface Call {
  id: string;
  agent_id: string;
  supervisor_id: string | null;
  call_time: string; // ISO timestamp
  duration: number; // seconds
  transcript: string | null;
  sentiment_score: number | null; // -1.0 to 1.0
  escalation_risk: EscalationRisk | null;
  created_at: string;
  updated_at: string;
}

export interface CallResponse {
  id: string;
  agentId: string;
  supervisorId: string | null;
  callTime: string;
  duration: number;
  transcript: string | null;
  sentimentScore: number | null;
  escalationRisk: EscalationRisk | null;
  createdAt: string;
}

// ============================================================================
// EVALUATION
// ============================================================================
export interface Evaluation {
  id: string;
  call_id: string;
  qa_score: number; // 0-100
  script_adherence_score: number; // 0-100
  resolution_correctness_score: number; // 0-100
  sop_violations: Record<string, string[]>;
  auto_generated: boolean;
  reviewed_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface EvaluationResponse {
  id: string;
  callId: string;
  qaScore: number;
  scriptAdherenceScore: number;
  resolutionCorrectnessScore: number;
  sopViolations: Record<string, string[]>;
  autoGenerated: boolean;
  reviewedBy: string | null;
  createdAt: string;
  averageScore?: number;
}

// ============================================================================
// COACHING INSIGHT
// ============================================================================
export interface CoachingInsight {
  id: string;
  agent_id: string;
  call_id: string;
  insight_text: string;
  priority: CoachingPriority;
  acknowledged: boolean;
  created_at: string;
}

export interface CoachingInsightResponse {
  id: string;
  agentId: string;
  callId: string;
  text: string;
  priority: CoachingPriority;
  acknowledged: boolean;
  createdAt: string;
}

// ============================================================================
// ALERT
// ============================================================================
export interface Alert {
  id: string;
  call_id: string;
  agent_id: string;
  severity: AlertSeverity;
  reason: string;
  resolved: boolean;
  created_at: string;
  updated_at: string;
}

export interface AlertResponse {
  id: string;
  callId: string;
  agentId: string;
  severity: AlertSeverity;
  reason: string;
  resolved: boolean;
  createdAt: string;
}

// ============================================================================
// SOP (Standard Operating Procedure)
// ============================================================================
export interface SOP {
  id: string;
  title: string;
  description: string | null;
  category: string | null;
  active: boolean;
  content: string | null;
  created_at: string;
  updated_at: string;
}

export interface SOPResponse {
  id: string;
  title: string;
  description: string | null;
  category: string | null;
  active: boolean;
  content: string | null;
}

// ============================================================================
// DASHBOARD STATS
// ============================================================================
export interface AgentStats {
  totalCalls: number;
  averageQaScore: number;
  totalCallDuration: number;
  escalationRate: number;
  thisWeekCalls: number;
  thisMonthCalls: number;
}

export interface SupervisorStats {
  teamSize: number;
  averageTeamQaScore: number;
  totalTeamCalls: number;
  lowPerformanceAgents: number;
  alertsThisWeek: number;
  callsThisWeek: number;
}

export interface AdminStats {
  totalUsers: number;
  totalAgents: number;
  totalCalls: number;
  averageQaScore: number;
  alertsUnresolved: number;
  callsThisMonth: number;
}

// ============================================================================
// AGENT DETAILS
// ============================================================================
export interface AgentDetail {
  id: string;
  name: string;
  email: string;
  totalCalls: number;
  averageQaScore: number;
  thisWeekCalls: number;
  lowQualityCalls: number;
}

// ============================================================================
// ANALYTICS
// ============================================================================
export interface TopAgent {
  name: string;
  averageQaScore: number;
  totalCalls: number;
}

export interface QualityTrend {
  week: number;
  score: number;
}

export interface AnalyticsResponse {
  topAgents: TopAgent[];
  lowPerformers: TopAgent[];
  qualityTrend: QualityTrend[];
}

// ============================================================================
// SETTINGS
// ============================================================================
export interface SettingsResponse {
  sopCategories: string[];
  escalationLevels: EscalationRisk[];
  roles: UserRole[];
  system: string;
}
